/*
 * @Author: Arthur arthur@lwork.com
 * @Date: 2024-10-13 16:53:53
 * @LastEditors: Arthur arthur@lwork.com
 * @LastEditTime: 2024-10-13 16:59:39
 * @FilePath: /texter/apps/texter/src/typings/EventType.ts
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
// 定义内置事件类型的枚举
export enum EventType {
  Click = 'click',
  DblClick = 'dblclick',
  MouseDown = 'mousedown',
  MouseEnter = 'mouseenter',
  MouseLeave = 'mouseleave',
  MouseMove = 'mousemove',
  MouseOver = 'mouseover',
  MouseOut = 'mouseout',
  MouseUp = 'mouseup',
  KeyDown = 'keydown',
  KeyPress = 'keypress',
  KeyUp = 'keyup',
  Abort = 'abort',
  BeforeUnload = 'beforeunload',
  Error = 'error',
  HashChange = 'hashchange',
  Load = 'load',
  PageHide = 'pagehide',
  PageShow = 'pageshow',
  Resize = 'resize',
  Scroll = 'scroll',
  Unload = 'unload',
  /** 表单事件 */
  Blur = 'blur',
  Change = 'change',
  Focus = 'focus',
  FocusIn = 'focusin',
  FocusOut = 'focusout',
  Input = 'input',
  Reset = 'reset',
  Search = 'search',
  Copy = 'copy',
  Cut = 'cut',
  Paste = 'paste',
  AfterPrint = 'afterprint',
  BeforePrint = 'beforeprint',
  Drag = 'drag',
  DragEnd = 'dragend',
  DragEnter = 'dragenter',
  DragLeave = 'dragleave',
  DragOver = 'dragover',
  DragStart = 'dragstart',
  Drop = 'drop',
  CanPlay = 'canplay',
  CanPlayThrough = 'canplaythrough',
  DurationChange = 'durationchange',
  Emptied = 'emptied',
  Ended = 'ended',
  LoadedData = 'loadeddata',
  LoadedMetadata = 'loadedmetadata',
  LoadStart = 'loadstart',
  Pause = 'pause',
  Play = 'play',
  Playing = 'playing',
  Progress = 'progress',
  RateChange = 'ratechange',
  Seeked = 'seeked',
  Seeking = 'seeking',
  Stall = 'stalled',
  Suspend = 'suspend',
  TimeUpdate = 'timeupdate',
  VolumeChange = 'volumechange',
  Waiting = 'waiting',
  AnimationEnd = 'animationend',
  AnimationIteration = 'animationiteration',
  AnimationStart = 'animationstart',
  TransitionEnd = 'transitionend',
  Message = 'message',
  Online = 'online',
  Offline = 'offline',
  PopState = 'popstate',
  Show = 'show',
}
